import { useMemo,useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function BusinessPortal(){
 const {user,logout}=useAuth(); const utils=trpc.useUtils(); const me=trpc.b2b.me.useQuery(); const catalog=trpc.b2b.catalog.useQuery(undefined,{enabled:me.data?.status==='APPROVED'}); const orders=trpc.b2b.myOrders.useQuery(); const [cart,setCart]=useState<Record<number,number>>({}); const [q,setQ]=useState('');
 const create=trpc.b2b.createOrder.useMutation({onSuccess:async()=>{setCart({});await Promise.all([utils.b2b.myOrders.invalidate(),utils.b2b.catalog.invalidate()])}});
 const items=useMemo(()=>catalog.data?.items.filter((x:any)=>`${x.sku} ${x.name} ${x.category_label||''}`.toLowerCase().includes(q.toLowerCase()))||[],[catalog.data,q]);
 if(!user)return null;
 return <main className="min-h-screen bg-[#f6f8f7]"><header className="bg-white border-b sticky top-0 z-10"><div className="max-w-7xl mx-auto px-4 py-3 flex items-center justify-between"><img src="/brand/ideal-prime-logo.jpg" className="h-12 object-contain"/><div className="text-right"><div className="font-medium">{me.data?.trade_name||me.data?.legal_name||user.name}</div><button className="text-sm text-[#067C52]" onClick={async()=>{await logout();location.href='/login'}}>Sair</button></div></div></header><div className="max-w-7xl mx-auto p-4 md:p-8">
 {me.isLoading?<p>Carregando...</p>:me.data?.status!=='APPROVED'?<section className="rounded-xl bg-white border p-8"><h1 className="text-xl font-semibold">Acesso empresarial em análise</h1><p className="mt-2 text-slate-600">A Ideal Prime ainda precisa aprovar sua empresa e liberar a tabela comercial antes do primeiro pedido.</p></section>:<>
 <div className="flex flex-col md:flex-row gap-4 md:items-end md:justify-between"><div><h1 className="text-2xl font-semibold">Catálogo empresarial</h1><p className="text-sm text-slate-600">Preços da tabela autorizada para sua empresa.</p></div><Input placeholder="Buscar por SKU, produto ou categoria" className="md:max-w-md bg-white" value={q} onChange={e=>setQ(e.target.value)}/></div>
 <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 mt-6">{items.map((p:any)=><article key={p.id} className="bg-white border rounded-xl overflow-hidden"><div className="aspect-square bg-slate-100 flex items-center justify-center">{p.image_url?<img src={p.image_url} className="w-full h-full object-contain"/>:<span className="text-slate-400">Sem imagem</span>}</div><div className="p-4"><div className="text-xs text-slate-500">{p.sku} · {p.unit}</div><h2 className="font-medium mt-1">{p.name}</h2><div className="font-semibold text-[#067C52] mt-2">{(p.price_cents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</div><div className="text-xs text-slate-500">Disponível: {p.available_quantity} · múltiplo {p.sales_multiple}</div><div className="flex gap-2 mt-3"><Input type="number" min={p.sales_multiple} step={p.sales_multiple} value={cart[p.id]||''} onChange={e=>setCart(c=>({...c,[p.id]:Number(e.target.value)}))}/></div></div></article>)}</div>
 <section className="mt-8 bg-white border rounded-xl p-5"><div className="flex justify-between items-center"><div><h2 className="font-semibold">Carrinho</h2><p className="text-sm text-slate-500">O servidor revalida preço, múltiplo e estoque antes de criar o pedido.</p></div><Button disabled={create.isPending||!Object.values(cart).some(Boolean)} onClick={()=>create.mutate({items:(Object.entries(cart) as [string, number][]).filter(([,qty])=>qty>0).map(([id,quantity])=>({productId:Number(id),quantity})),idempotencyKey:crypto.randomUUID(),paymentMethod:'MANUAL'})}>Enviar pedido</Button></div>{create.error&&<p className="text-sm text-red-600 mt-3">{create.error.message}</p>}</section>
 </>}
 <section className="mt-8"><h2 className="text-xl font-semibold mb-3">Meus pedidos</h2><div className="space-y-2">{orders.data?.map((o:any)=><div key={o.id} className="bg-white border rounded-lg p-4 flex justify-between"><div><strong>{o.order_number}</strong><div className="text-xs text-slate-500">{new Date(o.created_at).toLocaleString('pt-BR')}</div></div><div className="text-right"><div>{(o.total_cents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</div><div className="text-xs text-slate-500">{o.commercial_status} · {o.payment_status} · {o.fulfillment_status}</div></div></div>)}</div></section>
 </div></main>
}
